[package]
name = "example-bootloader"
version = "0.1.0"
edition = "2021"

[features]
defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "ec-slimloader/defmt",
    "embassy-imxrt/defmt",
    "embassy-executor/defmt",
    "partition-manager/defmt"
]

[dependencies]
ec-slimloader = { path = "../../../ec-slimloader", features = ["mimxrt685s-evk"], default-features = false }
example-bsp = { path = "../bsp", features = ["bootloader"] }

heapless = "0.9.1"

cortex-m = { version = "0.7.7", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = { version = "0.7.3" }

embassy-imxrt = { git = "https://github.com/Wassasin/embassy-imxrt.git", branch = "tmp/ec-slimloader-deps", default-features = false, features = [
    "mimxrt685s",
    "unstable-pac"
] }

embassy-executor = { git = "https://github.com/embassy-rs/embassy", features = [
    "arch-cortex-m",
    "executor-thread"
] }

embassy-sync = { git = "https://github.com/embassy-rs/embassy" }

partition-manager = { git = "https://github.com/OpenDevicePartnership/embedded-services.git", features = ["esa", "macros"], default-features = false }

defmt = { version = "0.3.6", optional = true }
defmt-rtt = { version = "0.4.0", optional = true }

panic-probe = "*"
